import '~/styles/globals.css'

import { Inter as FontSans } from 'next/font/google'

import { TRPCReactProvider } from '~/trpc/react'
import { cn } from '~/lib/utils'
import { Footer } from '~/components/layout/footer'
import { Navbar } from '~/components/layout/navbar'
import { ThemeProvider } from '~/components/theme-provider'

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
})
export const metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable,
				)}>
				<TRPCReactProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="dark"
						enableSystem
						disableTransitionOnChange>
						<div className="grid h-screen w-full grid-cols-1 grid-rows-[5rem_auto_5rem]">
							<Navbar />
							{children}
							<Footer />
						</div>
					</ThemeProvider>
				</TRPCReactProvider>
				{/* <Toaster /> */}
			</body>
			{/* <GoogleTagManager gtmId="GTM-MLT5XFTT" /> */}
		</html>
	)
}
