"""empty message

Revision ID: 34d647be67bb
Revises: f1a2b3c4d5e6
Create Date: 2026-03-08 00:46:04.724249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d647be67bb'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('alert_warning_pct', sa.Integer(), nullable=False, server_default='80'))
    op.add_column('budgets', sa.Column('alert_danger_pct', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'alert_danger_pct')
    op.drop_column('budgets', 'alert_warning_pct')
    # ### end Alembic commands ###
