"""empty message

Revision ID: a922ce3ebe51
Revises: 34d647be67bb
Create Date: 2026-03-08 14:44:58.892339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a922ce3ebe51'
down_revision: Union[str, Sequence[str], None] = '34d647be67bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'last_generated_at')
    # ### end Alembic commands ###
